categories:
  - title: "🚀 Features"
    label: "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧹 Chores"
    labels:
      - "chore"

exclude-labels:
  - "skip-changelog"

template: |
  ## What’s Changed
  $CHANGES

change-template: '- $TITLE (#$NUMBER)'
no-changes-template: '- No user-facing changes'

tag-template: v$NEXT_PATCH_VERSION
name-template: v$NEXT_PATCH_VERSION