name: Release

description: Create GitHub release and trigger NuGet deploy.

on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write

jobs:
  check-deploy-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for existing tag
        id: check-release
        run: |
          should_deploy="true"
          if [[ "${{ github.event_name }}" != "workflow_dispatch" ]]; then
            git fetch --tags origin ${{ github.sha }}
            tags=$(git tag --points-at ${{ github.sha }} --list 'v*')
            if [[ -n $tags ]]; then
              should_deploy="false"
            fi
          fi
          echo "should-deploy=$should_deploy" >> $GITHUB_OUTPUT
    outputs:
      should-deploy: ${{ steps.check-release.outputs.should-deploy }}

  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      - name: Run tests
        run: dotnet test ${{ vars.SOURCE_ROOT }} --configuration Release

  create-release:
    runs-on: ubuntu-latest
    needs: [ run-test, check-deploy-status ]
    if: ${{ needs.check-deploy-status.outputs.should-deploy == 'true' }}
    outputs:
      version-number: ${{ steps.version.outputs.version }}      # e.g. 1.2.3
      release-tag: ${{ steps.version.outputs.version_tag }}  # e.g. v1.2.3
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: paulhatch/semantic-version@v5.4.0
        id: version
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: true
          search_commit_body: true

      - uses: release-drafter/release-drafter@v6
        id: create-release
        with:
          name: ${{ steps.version.outputs.version }}
          tag: ${{ steps.version.outputs.version_tag }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

  deploy-nuget:
    uses: ./.github/workflows/deploy-nuget.yml
    needs: [ create-release, run-test ]
    secrets: inherit
    if: ${{ needs.create-release.outputs.release-tag != '' }}
    with:
      deploy: true
      version: ${{ needs.create-release.outputs.version-number }}
